### PR TITLE
Test on MacOS without latex

### PR DESCRIPTION
**Pull request by jeroen**

### CODE REVIEW

**Comment by s-u** [comment]
@jeroen thanks for trying. I'd prefer if we can fix the latex issue in the travis builds ;).

OT: gmp *is* available as 4.0.0 binary so there should be no need for homebrew:

```
> install.packages("gmp",,"http://cran")
trying URL 'http://cran/bin/macosx/contrib/4.0/gmp_0.5-13.6.tgz'
Content type 'application/x-gzip' length 885572 bytes (864 KB)
==================================================
downloaded 864 KB

```

**Comment by s-u** [comment]
BTW @jeroen let me know how I can help - I didn't find where it the code that defined the R language support, and how to test if one does changes in it. There are quite a few things that I wouldn't mind fixing.

**Comment by jeroen** [comment]
Where is `http://cran/` ? It seems the latest R-devel for Mac is still building all packages from source? 🤔 

The travis R template is define here: https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb . But you should know that people are moving away from Travis because they are not very comitted anymore to maintaining R language support.

Github actions is the new thing :-) I'll set that up for you in a separate pr.

**Comment by jeroen** [comment]
It fails now because R-devel is trying to access: `https://cloud.r-project.org/bin/macosx/el-capitan/contrib/4.0` which does not exist...

**Comment by jeroen** [comment]
I see now, we are using the el-capitain version of the R-devel installer: https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb#L128-L129

What is the canonical URL to get grab the latest R-devel installer package?

**Comment by s-u** [comment]
https://mac.r-project.org/high-sierra/R-4.0-branch/R-4.0-branch.pkg
and
https://mac.r-project.org/high-sierra/R-devel/R-devel.pkg

Note that devel won't have binary packages, but R-4.0-branch will.

FWIW we just discussed that recently with Jim at https://github.com/r-lib/actions/pull/68#issuecomment-610374168

**Comment by s-u** [comment]
I had a quick look at Github actions, but the support there is a lot worse - if I saw it correctly you can't even pick macOS version.

**Comment by jeroen** [comment]
Ah okay. It looks like there is a PR already to update this at travis but it hasn't been merged yet: https://github.com/travis-ci/travis-build/pull/1885

So the problem will get fixed, eventually, when travis maintainers get to it...

**Comment by s-u** [comment]
Ah, ok, that is rather bad. I see what you meant. I'm also getting random failures right now:
https://travis-ci.org/github/cloudyr/aws.s3/builds/673383841
so I suppose it's time to roll out my own build system without using the language support...

**Comment by s-u** [comment]
This was a test showing how the Travis CI is broken on macOS

**Pull request closed without merging**
